-- Seed generated from delete111.xlsx on 2026-04-07
begin;
with seed_raw(digit_position, option_name, code_value, choice_value) as ( values
  (1, 'HandlebarType', '1', 'Small'),
  (1, 'HandlebarType', '2', 'Medium'),
  (1, 'HandlebarType', '3', 'Large'),
  (1, 'HandlebarType', 'A', 'A Line'),
  (1, 'HandlebarType', 'H', 'High'),
  (1, 'HandlebarType', 'M', 'Mid'),
  (1, 'HandlebarType', 'S', 'Low'),
  (2, 'Speeds', '1', 'One - 1 Speed'),
  (2, 'Speeds', '2', 'Urban - 2 Speeds'),
  (2, 'Speeds', '3', 'Utility - 3 Speeds'),
  (2, 'Speeds', '4', 'Urban - 4 Speeds'),
  (2, 'Speeds', '6', 'Explore - 6 Speeds'),
  (2, 'Speeds', '8', 'TBC - 8 Speeds'),
  (2, 'Speeds', 'L', 'Explore - 12 Speeds'),
  (3, 'MudguardsAndRack', 'E', 'No Mudguards - E-Version'),
  (3, 'MudguardsAndRack', 'L', 'Mudguards - L-Version'),
  (3, 'MudguardsAndRack', 'R', 'Mudguards and Rack - R-Version'),
  (4, 'Territory', '0', 'Code Not in Use'),
  (5, 'MainFrameColour', '1', 'Lunar Ice'),
  (5, 'MainFrameColour', '2', 'Cerakote Ti Black'),
  (5, 'MainFrameColour', '4', 'Forest Green'),
  (5, 'MainFrameColour', '5', 'Traildust White'),
  (5, 'MainFrameColour', '6', 'Adventure Orange'),
  (5, 'MainFrameColour', '9', 'Blasted Ti'),
  (5, 'MainFrameColour', 'A', 'Bumblebee Yellow'),
  (5, 'MainFrameColour', 'B', 'Black - Matt'),
  (5, 'MainFrameColour', 'E', 'Ocean Blue'),
  (5, 'MainFrameColour', 'F', 'Amethyst Lacquer'),
  (5, 'MainFrameColour', 'G', 'Racing Green - Matt'),
  (5, 'MainFrameColour', 'K', 'Black Lacquer - Gloss'),
  (5, 'MainFrameColour', 'N', 'Dune Sand'),
  (5, 'MainFrameColour', 'O', 'Bottle Green'),
  (5, 'MainFrameColour', 'R', 'Turkish Green - Matt'),
  (5, 'MainFrameColour', 'S', 'Papyrus White - Matt'),
  (5, 'MainFrameColour', 'T', 'Midnight Black Metallic'),
  (5, 'MainFrameColour', 'V', 'Bolt Blue Lacquer'),
  (5, 'MainFrameColour', 'W', 'Yuzu Lime'),
  (5, 'MainFrameColour', 'X', 'Special Colour X'),
  (5, 'MainFrameColour', 'Y', 'Special Colour Y'),
  (5, 'MainFrameColour', 'Z', 'Special Colour Z'),
  (5, 'MainFrameColour', '3', 'Space Black'),
  (5, 'MainFrameColour', 'J', 'Flamingo Pink'),
  (5, 'MainFrameColour', 'M', 'Metallic Green Gloss'),
  (5, 'MainFrameColour', 'D', 'Cobalt Blue Lacquer'),
  (5, 'MainFrameColour', 'H', 'Lavender Matt'),
  (5, 'MainFrameColour', 'L', 'Metallic Blue Gloss'),
  (5, 'MainFrameColour', 'U', 'Palm Green'),
  (5, 'MainFrameColour', 'Q', 'Wine Red Matt'),
  (5, 'MainFrameColour', 'C', 'Veligo Blue'),
  (5, 'MainFrameColour', '8', 'Purple Violet'),
  (5, 'MainFrameColour', 'P', 'Pale Brown'),
  (5, 'MainFrameColour', '7', 'Azure Blue'),
  (6, 'RearFrameColour', '1', 'Lunar Ice'),
  (6, 'RearFrameColour', '2', 'Cerakote Ti Black'),
  (6, 'RearFrameColour', '4', 'Forest Green'),
  (6, 'RearFrameColour', '5', 'Traildust White'),
  (6, 'RearFrameColour', '6', 'Adventure Orange'),
  (6, 'RearFrameColour', '9', 'Blasted Titanium'),
  (6, 'RearFrameColour', 'A', 'Bumblebee Yellow'),
  (6, 'RearFrameColour', 'B', 'Black - Matt'),
  (6, 'RearFrameColour', 'E', 'Ocean Blue'),
  (6, 'RearFrameColour', 'F', 'Amethyst Lacquer'),
  (6, 'RearFrameColour', 'G', 'Racing Green - Matt'),
  (6, 'RearFrameColour', 'K', 'Black Lacquer - Gloss'),
  (6, 'RearFrameColour', 'N', 'Dune Sand'),
  (6, 'RearFrameColour', 'O', 'Bottle Green'),
  (6, 'RearFrameColour', 'R', 'Turkish Green - Matt'),
  (6, 'RearFrameColour', 'V', 'Bolt Blue Lacquer'),
  (6, 'RearFrameColour', 'W', 'Yuzu Lime'),
  (6, 'RearFrameColour', 'X', 'Special Colour X'),
  (6, 'RearFrameColour', 'Y', 'Special Colour Y'),
  (6, 'RearFrameColour', 'Z', 'Special Colour Z'),
  (6, 'RearFrameColour', '3', 'Space Black'),
  (6, 'RearFrameColour', 'J', 'Flamingo Pink'),
  (6, 'RearFrameColour', 'M', 'Metallic Green Gloss'),
  (6, 'RearFrameColour', 'D', 'Cobalt Blue Lacquer'),
  (6, 'RearFrameColour', 'H', 'Lavender Matt'),
  (6, 'RearFrameColour', 'L', 'Metallic Blue Gloss'),
  (6, 'RearFrameColour', 'U', 'Palm Green'),
  (6, 'RearFrameColour', 'Q', 'Wine Red Matt'),
  (6, 'RearFrameColour', 'S', 'Gloss White'),
  (6, 'RearFrameColour', 'C', 'Veligo Blue'),
  (6, 'RearFrameColour', '8', 'Purple Violet'),
  (6, 'RearFrameColour', 'T', 'Midnight Black Metallic'),
  (6, 'RearFrameColour', 'P', 'Pale Brown'),
  (6, 'RearFrameColour', '7', 'Azure Blue'),
  (7, 'FrontCarrierBlock', '0', 'No front carrier block'),
  (7, 'FrontCarrierBlock', '1', 'Bomber Front End Carrier Block - Category Electric'),
  (7, 'FrontCarrierBlock', '2', 'forged front carrier block'),
  (7, 'FrontCarrierBlock', 'A', 'Front Carrier Block - Electric Brixton'),
  (7, 'FrontCarrierBlock', 'B', 'Front Carrier Block'),
  (7, 'FrontCarrierBlock', 'E', 'Front Carrier Block - Bromtpon Electric'),
  (7, 'FrontCarrierBlock', 'G', 'Front Carrier Block - B Electric Greenway'),
  (8, 'Lighting', '0', 'Refls only NO LIGHTS'),
  (8, 'Lighting', '1', 'Rechargeable Battery - Lezyne Hecto Drive 500 XL'),
  (8, 'Lighting', '2', 'Rechargeable Battery - Lezyne Hecto 40'),
  (8, 'Lighting', '3', 'New Brixton E-Bike Light'),
  (8, 'Lighting', 'B', 'BAT lamps Front and Rear'),
  (8, 'Lighting', 'C', 'B+M AVY Integrated Lights on Brompton Electric'),
  (8, 'Lighting', 'D', 'G Volt 60 Battery lamps Front and Rear'),
  (8, 'Lighting', 'E', 'Lezyne E115'),
  (8, 'Lighting', 'S', 'SP Hub Dynamo (SV-8)'),
  (9, 'SaddleHeight', '0', 'Standard seat post'),
  (9, 'SaddleHeight', '6', 'Extended seat post'),
  (9, 'SaddleHeight', 'A', 'Telescopic seat post'),
  (9, 'SaddleHeight', 'B', 'Superlight Standard'),
  (9, 'SaddleHeight', 'C', 'Superlight Extended'),
  (9, 'SaddleHeight', 'T', 'Superlight Telescopic'),
  (10, 'GearRatio', '0', 'Standard Gearing'),
  (10, 'GearRatio', 'A', '44T Chainring'),
  (10, 'GearRatio', 'B', '50T Chainring'),
  (10, 'GearRatio', 'C', '54T Chainring'),
  (10, 'GearRatio', 'D', '56T Chainring'),
  (10, 'GearRatio', 'I', 'Increased Gearing'),
  (10, 'GearRatio', 'R', 'Reduced Gearing'),
  (11, 'Saddle', '0', 'Saddle Standard'),
  (11, 'Saddle', '1', 'Custom Saddle'),
  (11, 'Saddle', '2', 'City + Comfy Saddle'),
  (11, 'Saddle', '3', 'Custom AndWander'),
  (11, 'Saddle', '4', 'Brooks B17 Green'),
  (11, 'Saddle', '5', 'Brooks C17 Barbour'),
  (11, 'Saddle', '6', 'Standard Custom'),
  (11, 'Saddle', '7', 'Fizik Aliante R7'),
  (11, 'Saddle', 'A', 'Brooks Cambium C17 All Weather'),
  (11, 'Saddle', 'B', 'Saddle Brooks B17 Special Men'),
  (11, 'Saddle', 'C', 'Saddle Brooks B17 Black Men'),
  (11, 'Saddle', 'D', 'A-Line Saddle'),
  (11, 'Saddle', 'F', 'Custom Saddle - P-TDF'),
  (11, 'Saddle', 'G', 'Custom Saddle - C-TDF'),
  (11, 'Saddle', 'H', 'Saddle Chateaux'),
  (11, 'Saddle', 'L', 'Saddle Brooks B17 Special Female'),
  (11, 'Saddle', 'O', 'Superlight Saddle'),
  (11, 'Saddle', 'Q', 'Saddle Brooks Cambium All Weather TeamGB'),
  (11, 'Saddle', 'T', 'Superlight Carbon Saddle'),
  (11, 'Saddle', 'U', 'Ultra Saddle With Titanium Rails CHPT3'),
  (11, 'Saddle', 'V', 'Custom Saddle - Velo White'),
  (11, 'Saddle', 'W', 'Saddle Standard Wide'),
  (11, 'Saddle', 'X', 'Fizik Terra Argo'),
  (12, 'Tyre', '0', 'Schwalbe Marathon Racer Tyre'),
  (12, 'Tyre', '1', 'Schwalbe ONE Tanwall Tyre'),
  (12, 'Tyre', '2', 'Schwalbe ONE Black Tyre'),
  (12, 'Tyre', '3', 'Conti Tyre Black/Tan 20in'),
  (12, 'Tyre', '4', 'Schwalbe Big Apple Black'),
  (12, 'Tyre', '5', 'Schwalbe Marathon Almotion'),
  (12, 'Tyre', '6', 'Custom AndWander'),
  (12, 'Tyre', 'A', 'A Line Schwalbe Marathon Racer'),
  (12, 'Tyre', 'C', 'Continental Contact Urban 16in'),
  (12, 'Tyre', 'D', 'CONTINENTAL CONTACT URBAN CREAM'),
  (12, 'Tyre', 'G', 'Schwalbe G-One All Round 54-406. Tan wall'),
  (12, 'Tyre', 'J', 'Schwalbe Kojak Tyre'),
  (12, 'Tyre', 'K', 'A Line Schwalbe Kojak Tyre'),
  (12, 'Tyre', 'M', 'Schwalbe Marathon Tyre'),
  (12, 'Tyre', 'R', 'Pirelli Angel RS Black Sidewall'),
  (12, 'Tyre', 'T', 'Marathon Tanwall (Folding) Tyre'),
  (13, 'Brakes', '0', 'Brakes FWD Orientation'),
  (13, 'Brakes', 'R', 'Brakes REV Orientation'),
  (14, 'Pedals', '0', 'Folding pedal LH & RH std'),
  (14, 'Pedals', 'N', 'No Folding pedal LH & RH std'),
  (14, 'Pedals', 'Q', 'Quick Release'),
  (15, 'Saddlebag', '0', 'Code Not in Use'),
  (15, 'Saddlebag', '1', 'Saddle bag Chateaux'),
  (15, 'Saddlebag', '2', 'Leather Saddle Roll Bag'),
  (16, 'Suspension', '0', 'Std Suspension pad WITH clip'),
  (16, 'Suspension', 'F', 'Firm Suspension pad with clip'),
  (16, 'Suspension', 'R', 'Red Xtra Firm Suspension Block - w/ clip'),
  (16, 'Suspension', 'W', 'White Suspension Block'),
  (17, 'BikeType', '0', 'C Line'),
  (17, 'BikeType', '1', 'C Line Demo'),
  (17, 'BikeType', '2', 'P Line BBC'),
  (17, 'BikeType', '4', 'C Line TeamGB Staff'),
  (17, 'BikeType', '5', 'C Line Barbour Edition'),
  (17, 'BikeType', '6', 'C Line Millionth Edition'),
  (17, 'BikeType', '7', 'NA Artist C Line'),
  (17, 'BikeType', '8', 'C Line TDF'),
  (17, 'BikeType', '9', 'C Line Classic Silver'),
  (17, 'BikeType', 'A', 'A Line'),
  (17, 'BikeType', 'B', 'C Line Black Edition'),
  (17, 'BikeType', 'E', 'C Line Electric'),
  (17, 'BikeType', 'F', 'C Line Electric Demo'),
  (17, 'BikeType', 'G', 'G Line'),
  (17, 'BikeType', 'H', 'G Line Electric'),
  (17, 'BikeType', 'I', 'P Line'),
  (17, 'BikeType', 'J', 'P Line Electric'),
  (17, 'BikeType', 'K', 'P Line Demo'),
  (17, 'BikeType', 'L', 'P Line Shenzhen Junction'),
  (17, 'BikeType', 'M', 'P Line Electric Demo'),
  (17, 'BikeType', 'N', 'C Line Nickel'),
  (17, 'BikeType', 'O', 'C Line Team GB Edition'),
  (17, 'BikeType', 'R', 'C Line Beyond Edition'),
  (17, 'BikeType', 'S', 'G Line Electric Demo'),
  (17, 'BikeType', 'T', 'T Line'),
  (17, 'BikeType', 'V', 'T Line Demo'),
  (17, 'BikeType', 'W', 'G Line Demo'),
  (17, 'BikeType', 'X', 'Special Colour BED'),
  (17, 'BikeType', 'Y', 'C Line 50th Anniversary'),
  (17, 'BikeType', '3', 'C Line Electric MK6'),
  (17, 'BikeType', 'D', 'C Line Electric Brixton'),
  (17, 'BikeType', 'U', 'T Line Electric'),
  (17, 'BikeType', 'C', 'C Line MK6'),
  (17, 'BikeType', 'Q', 'P Line Electric Brixton'),
  (17, 'BikeType', 'P', 'P Line'),
  (18, 'Toolkit', '0', 'Code Not in Use'),
  (18, 'Toolkit', '1', 'Brompton Toolkit'),
  (19, 'SaddleLight', '0', 'Code Not in Use'),
  (20, 'ConfigurationCode', '1', 'MY20'),
  (20, 'ConfigurationCode', '2', 'MY21'),
  (20, 'ConfigurationCode', '3', 'MY22'),
  (20, 'ConfigurationCode', '4', 'MY23'),
  (20, 'ConfigurationCode', '5', 'MY24'),
  (20, 'ConfigurationCode', '6', 'MY25 Version'),
  (20, 'ConfigurationCode', '7', 'MY26 Version'),
  (21, 'OptionsBox(Electriconly)', '0', 'None'),
  (21, 'OptionsBox(Electriconly)', '1', 'Option Box 1 - Bag - Charger - UK Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', '2', 'Option Box 2 - Batt-Bag-Charger-UK Plug & Man'),
  (21, 'OptionsBox(Electriconly)', '3', 'Option Box 3 - Bag - Charger - EU Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', '4', 'Option Box 4 - Batt,Bag-Charger-EU Plug & Man'),
  (21, 'OptionsBox(Electriconly)', '5', 'Option Box 5 - Bag - Charger - US Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', '6', 'Option Box 6 - Batt-Bag-Charger-US Plug & Man'),
  (21, 'OptionsBox(Electriconly)', '7', 'Option Box 7 - Manual Only'),
  (21, 'OptionsBox(Electriconly)', '8', 'Option Box 8 - Bag - Charger - AU Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', '9', 'Option Box 9 - Batt-Bag-Charger-AU Plug & Man'),
  (21, 'OptionsBox(Electriconly)', 'A', 'Option Box A - Bag - Charger - US Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', 'B', 'Option Box 12 - Batt-Bag-Charger-US Plug & Man'),
  (21, 'OptionsBox(Electriconly)', 'E', 'GE Line Greenway Battery, Small bag, 2A charger UK.'),
  (21, 'OptionsBox(Electriconly)', 'F', 'GE Line Greenway Battery, Small bag, 2A charger EU.'),
  (21, 'OptionsBox(Electriconly)', 'G', 'GE Line Greenway Battery, Small bag, 2A charger US.'),
  (21, 'OptionsBox(Electriconly)', 'H', 'GE Line Greenway Battery, Small bag, 2A charger AU/NZ.'),
  (22, 'FrameMaterial', 'T', 'All Titanium - Mk6 Extremities'),
  (22, 'FrameSet', '1', 'Standard'),
  (22, 'FrameSet', '2', 'Demo'),
  (22, 'FrameSet', '3', 'Special NA Artist V2'),
  (22, 'FrameSet', '4', 'Special Comfort(City+)'),
  (22, 'FrameSet', '5', 'Special Veligo'),
  (22, 'FrameSet', '6', 'APAC Urban Outdoor'),
  (22, 'FrameSet', '7', 'APAC Premium Silver'),
  (22, 'FrameSet', '8', 'Freelander'),
  (22, 'FrameSet', '9', 'Vitality'),
  (23, 'ComponentColour', '1', 'Silver'),
  (23, 'ComponentColour', '2', 'Black'),
  (24, 'OnBikeAccessories', '0', 'None'),
  (24, 'OnBikeAccessories', '5', 'Lezyne Pump and Mounts'),
  (24, 'OnBikeAccessories', 'A', 'DTH Kit'),
  (24, 'OnBikeAccessories', 'B', 'DTH Kit FR Reg'),
  (24, 'OnBikeAccessories', 'C', 'DTH Kit & Lezyne Pump and Mounts'),
  (24, 'OnBikeAccessories', 'D', 'DTH Kit FR Reg & Lezyne Pump and Mounts'),
  (24, 'OnBikeAccessories', 'E', 'DTH Kit A-Line & Zefal Brompton Pump'),
  (24, 'OnBikeAccessories', 'F', 'DTH Kit A-Line FR Reg & Zefal Brompton Pump'),
  (24, 'OnBikeAccessories', 'G', 'DTH Kit A-Line'),
  (24, 'OnBikeAccessories', 'H', 'DTH Kit A-Line FR Reg'),
  (24, 'OnBikeAccessories', 'M', 'Flexi Mudguard'),
  (24, 'OnBikeAccessories', 'S', 'Lezyne Pump Silver'),
  (24, 'OnBikeAccessories', 'Z', 'Zefal Brompton Pump'),
  (25, 'HandlebarStemColour', '1', 'Lunar Ice'),
  (25, 'HandlebarStemColour', '2', 'Cerakote Ti Black'),
  (25, 'HandlebarStemColour', '3', 'Pure Orange Matt'),
  (25, 'HandlebarStemColour', '4', 'Forest Green'),
  (25, 'HandlebarStemColour', '5', 'Baby Pink'),
  (25, 'HandlebarStemColour', '6', 'Tempest Blue'),
  (25, 'HandlebarStemColour', '8', 'Pall Mall White Gloss'),
  (25, 'HandlebarStemColour', '9', 'Blasted Titanium'),
  (25, 'HandlebarStemColour', 'A', 'Bumblebee Yellow'),
  (25, 'HandlebarStemColour', 'B', 'Black - Matt'),
  (25, 'HandlebarStemColour', 'D', 'Oxblood Red Gloss'),
  (25, 'HandlebarStemColour', 'E', 'Ocean Blue'),
  (25, 'HandlebarStemColour', 'F', 'Amethyst Lacquer'),
  (25, 'HandlebarStemColour', 'G', 'Racing Green - Matt'),
  (25, 'HandlebarStemColour', 'K', 'Black Lacquer - Gloss'),
  (25, 'HandlebarStemColour', 'M', 'Bronze Sky Metallic'),
  (25, 'HandlebarStemColour', 'N', 'Dune Sand'),
  (25, 'HandlebarStemColour', 'O', 'Bottle Green'),
  (25, 'HandlebarStemColour', 'R', 'Turkish Green - Matt'),
  (25, 'HandlebarStemColour', 'S', 'Papyrus White - Matt'),
  (25, 'HandlebarStemColour', 'T', 'Midnight Black Metallic'),
  (25, 'HandlebarStemColour', 'V', 'Bolt Blue Lacquer'),
  (25, 'HandlebarStemColour', 'W', 'Yuzu Lime'),
  (25, 'HandlebarStemColour', 'X', 'Special Colour X'),
  (25, 'HandlebarStemColour', 'Y', 'Special Colour Y'),
  (25, 'HandlebarStemColour', 'Z', 'Special Colour Z'),
  (25, 'HandlebarStemColour', 'J', 'Flamingo Pink'),
  (25, 'HandlebarStemColour', 'H', 'Lavender Matt'),
  (25, 'HandlebarStemColour', 'L', 'Metallic Blue Gloss'),
  (25, 'HandlebarStemColour', 'U', 'Palm Green'),
  (25, 'HandlebarStemColour', 'Q', 'Wine Red Matt'),
  (25, 'HandlebarStemColour', 'C', 'Veligo Blue'),
  (25, 'HandlebarStemColour', 'P', 'Pale Brown'),
  (25, 'HandlebarStemColour', '7', 'Azure Blue'),
  (26, 'HandlebarPinColour', '1', 'Lunar Ice'),
  (26, 'HandlebarPinColour', '2', 'Yellow Gloss'),
  (26, 'HandlebarPinColour', '3', 'Pure Orange Matt'),
  (26, 'HandlebarPinColour', '4', 'White - Gloss'),
  (26, 'HandlebarPinColour', '5', 'Baby Pink'),
  (26, 'HandlebarPinColour', '6', 'Tempest Blue'),
  (26, 'HandlebarPinColour', '7', 'Laurel Green Gloss'),
  (26, 'HandlebarPinColour', '9', 'Blasted Ti'),
  (26, 'HandlebarPinColour', 'A', 'Bumblebee Yellow'),
  (26, 'HandlebarPinColour', 'B', 'Black - Matt'),
  (26, 'HandlebarPinColour', 'D', 'Oxblood Red Gloss'),
  (26, 'HandlebarPinColour', 'E', 'Ocean Blue'),
  (26, 'HandlebarPinColour', 'F', 'Amethyst Lacquer'),
  (26, 'HandlebarPinColour', 'G', 'Racing Green - Matt'),
  (26, 'HandlebarPinColour', 'K', 'Black Lacquer - Gloss'),
  (26, 'HandlebarPinColour', 'M', 'Bronze Sky Metallic'),
  (26, 'HandlebarPinColour', 'N', 'Dune Sand'),
  (26, 'HandlebarPinColour', 'O', 'Bottle Green'),
  (26, 'HandlebarPinColour', 'R', 'Turkish Green - Matt'),
  (26, 'HandlebarPinColour', 'T', 'Midnight Black Metallic'),
  (26, 'HandlebarPinColour', 'V', 'Bolt Blue Lacquer'),
  (26, 'HandlebarPinColour', 'W', 'Sulphur Yellow'),
  (26, 'HandlebarPinColour', 'X', 'Special Colour X'),
  (26, 'HandlebarPinColour', 'Y', 'Special Colour Y'),
  (26, 'HandlebarPinColour', 'Z', 'Special Colour Z'),
  (26, 'HandlebarPinColour', 'J', 'Flamingo Pink'),
  (26, 'HandlebarPinColour', 'S', 'Gloss White'),
  (26, 'HandlebarPinColour', 'H', 'Lavender Matt'),
  (26, 'HandlebarPinColour', 'L', 'Metallic Blue Gloss'),
  (26, 'HandlebarPinColour', 'U', 'Palm Green'),
  (26, 'HandlebarPinColour', 'Q', 'Wine Red Matt'),
  (26, 'HandlebarPinColour', 'C', 'Veligo Blue'),
  (26, 'HandlebarPinColour', 'P', 'Pale Brown'),
  (26, 'HandlebarPinColour', '8', 'Purple Violet'),
  (27, 'FrontFrameColour', '1', 'Lunar Ice'),
  (27, 'FrontFrameColour', '4', 'Forest Green'),
  (27, 'FrontFrameColour', '5', 'Traildust White'),
  (27, 'FrontFrameColour', '6', 'Adventure Orange'),
  (27, 'FrontFrameColour', '7', 'Laurel Green Gloss'),
  (27, 'FrontFrameColour', '9', 'Blasted Ti'),
  (27, 'FrontFrameColour', 'B', 'Black - Matt'),
  (27, 'FrontFrameColour', 'C', 'Cerakote Ti Red'),
  (27, 'FrontFrameColour', 'F', 'Amethyst Lacquer'),
  (27, 'FrontFrameColour', 'G', 'Racing Green - Matt'),
  (27, 'FrontFrameColour', 'K', 'Black Lacquer - Gloss'),
  (27, 'FrontFrameColour', 'N', 'Dune Sand'),
  (27, 'FrontFrameColour', 'O', 'Bottle Green'),
  (27, 'FrontFrameColour', 'R', 'Turkish Green - Matt'),
  (27, 'FrontFrameColour', 'S', 'Papyrus White - Matt'),
  (27, 'FrontFrameColour', 'T', 'Midnight Black Metallic'),
  (27, 'FrontFrameColour', 'V', 'Bolt Blue Lacquer'),
  (27, 'FrontFrameColour', 'W', 'Sulphur Yellow'),
  (27, 'FrontFrameColour', 'X', 'Special Colour X'),
  (27, 'FrontFrameColour', 'Y', 'Special Colour Y'),
  (27, 'FrontFrameColour', 'Z', 'Special Colour Z'),
  (27, 'FrontFrameColour', '3', 'Space Black'),
  (27, 'FrontFrameColour', 'J', 'Flamingo Pink'),
  (27, 'FrontFrameColour', 'M', 'Metallic Green Gloss'),
  (27, 'FrontFrameColour', 'D', 'Cobalt Blue Lacquer'),
  (27, 'FrontFrameColour', 'H', 'Lavender Matt'),
  (27, 'FrontFrameColour', 'L', 'Metallic Blue Gloss'),
  (27, 'FrontFrameColour', 'U', 'Palm Green'),
  (27, 'FrontFrameColour', 'Q', 'Wine Red Matt'),
  (27, 'FrontFrameColour', '2', 'Beige Grey'),
  (27, 'FrontFrameColour', 'A', 'Pastel Violet'),
  (27, 'FrontFrameColour', 'P', 'Pale Brown'),
  (27, 'FrontFrameColour', '8', 'Purple Violet'),
  (27, 'FrontFrameColour', 'E', 'Vitality Pink'),
  (28, 'FrontForkColour', '1', 'Lunar Ice'),
  (28, 'FrontForkColour', '2', 'Yellow Gloss'),
  (28, 'FrontForkColour', '4', 'Forest Green'),
  (28, 'FrontForkColour', '5', 'Traildust White'),
  (28, 'FrontForkColour', '6', 'Adventure Orange'),
  (28, 'FrontForkColour', '7', 'Laurel Green Gloss'),
  (28, 'FrontForkColour', '9', 'Blasted Titanium'),
  (28, 'FrontForkColour', 'A', 'Bumblebee Yellow'),
  (28, 'FrontForkColour', 'B', 'Black - Matt'),
  (28, 'FrontForkColour', 'D', 'Oxblood Red Gloss'),
  (28, 'FrontForkColour', 'E', 'Ocean Blue'),
  (28, 'FrontForkColour', 'F', 'Amethyst Lacquer'),
  (28, 'FrontForkColour', 'G', 'Racing Green - Matt'),
  (28, 'FrontForkColour', 'K', 'Black Lacquer - Gloss'),
  (28, 'FrontForkColour', 'M', 'Bronze Sky Metallic'),
  (28, 'FrontForkColour', 'N', 'Dune Sand'),
  (28, 'FrontForkColour', 'O', 'Bottle Green'),
  (28, 'FrontForkColour', 'R', 'Turkish Green - Matt'),
  (28, 'FrontForkColour', 'S', 'Papyrus White - Matt'),
  (28, 'FrontForkColour', 'T', 'Midnight Black Metallic'),
  (28, 'FrontForkColour', 'V', 'Bolt Blue Lacquer'),
  (28, 'FrontForkColour', 'W', 'Sulphur Yellow'),
  (28, 'FrontForkColour', 'X', 'Special Colour X'),
  (28, 'FrontForkColour', 'Y', 'Special Colour Y'),
  (28, 'FrontForkColour', 'Z', 'Special Colour Z'),
  (28, 'FrontForkColour', '3', 'Space Black'),
  (28, 'FrontForkColour', 'J', 'Flamingo Pink'),
  (28, 'FrontForkColour', 'H', 'Lavender Matt'),
  (28, 'FrontForkColour', 'L', 'Piccadilly Blue'),
  (28, 'FrontForkColour', 'U', 'Palm Green'),
  (28, 'FrontForkColour', 'Q', 'Wine Red Matt'),
  (28, 'FrontForkColour', 'C', 'Veligo Blue'),
  (28, 'FrontForkColour', 'P', 'Pale Brown'),
  (28, 'FrontForkColour', '8', 'Purple Violet'),
  (29, 'Position29', '1', 'Code 1'),
  (30, 'Grade', '0', 'New'),
  (30, 'Grade', 'A', 'Grade A'),
  (30, 'Grade', 'B', 'Grade B'),
  (30, 'Grade', 'C', 'Grade C')
),
seed as ( select digit_position, option_name, upper(code_value) as code_value, choice_value from seed_raw )
update sku_rules r set option_name = s.option_name, choice_value = s.choice_value, is_active = true, deactivated_at = null, deactivation_reason = null from seed s where ((s.digit_position > 0 and r.digit_position = s.digit_position and upper(r.code_value) = s.code_value) or (s.digit_position = 0 and r.digit_position = 0 and lower(r.option_name) = lower(s.option_name) and upper(r.code_value) = s.code_value)) and r.is_active = true;
with seed_raw(digit_position, option_name, code_value, choice_value) as ( values
  (1, 'HandlebarType', '1', 'Small'),
  (1, 'HandlebarType', '2', 'Medium'),
  (1, 'HandlebarType', '3', 'Large'),
  (1, 'HandlebarType', 'A', 'A Line'),
  (1, 'HandlebarType', 'H', 'High'),
  (1, 'HandlebarType', 'M', 'Mid'),
  (1, 'HandlebarType', 'S', 'Low'),
  (2, 'Speeds', '1', 'One - 1 Speed'),
  (2, 'Speeds', '2', 'Urban - 2 Speeds'),
  (2, 'Speeds', '3', 'Utility - 3 Speeds'),
  (2, 'Speeds', '4', 'Urban - 4 Speeds'),
  (2, 'Speeds', '6', 'Explore - 6 Speeds'),
  (2, 'Speeds', '8', 'TBC - 8 Speeds'),
  (2, 'Speeds', 'L', 'Explore - 12 Speeds'),
  (3, 'MudguardsAndRack', 'E', 'No Mudguards - E-Version'),
  (3, 'MudguardsAndRack', 'L', 'Mudguards - L-Version'),
  (3, 'MudguardsAndRack', 'R', 'Mudguards and Rack - R-Version'),
  (4, 'Territory', '0', 'Code Not in Use'),
  (5, 'MainFrameColour', '1', 'Lunar Ice'),
  (5, 'MainFrameColour', '2', 'Cerakote Ti Black'),
  (5, 'MainFrameColour', '4', 'Forest Green'),
  (5, 'MainFrameColour', '5', 'Traildust White'),
  (5, 'MainFrameColour', '6', 'Adventure Orange'),
  (5, 'MainFrameColour', '9', 'Blasted Ti'),
  (5, 'MainFrameColour', 'A', 'Bumblebee Yellow'),
  (5, 'MainFrameColour', 'B', 'Black - Matt'),
  (5, 'MainFrameColour', 'E', 'Ocean Blue'),
  (5, 'MainFrameColour', 'F', 'Amethyst Lacquer'),
  (5, 'MainFrameColour', 'G', 'Racing Green - Matt'),
  (5, 'MainFrameColour', 'K', 'Black Lacquer - Gloss'),
  (5, 'MainFrameColour', 'N', 'Dune Sand'),
  (5, 'MainFrameColour', 'O', 'Bottle Green'),
  (5, 'MainFrameColour', 'R', 'Turkish Green - Matt'),
  (5, 'MainFrameColour', 'S', 'Papyrus White - Matt'),
  (5, 'MainFrameColour', 'T', 'Midnight Black Metallic'),
  (5, 'MainFrameColour', 'V', 'Bolt Blue Lacquer'),
  (5, 'MainFrameColour', 'W', 'Yuzu Lime'),
  (5, 'MainFrameColour', 'X', 'Special Colour X'),
  (5, 'MainFrameColour', 'Y', 'Special Colour Y'),
  (5, 'MainFrameColour', 'Z', 'Special Colour Z'),
  (5, 'MainFrameColour', '3', 'Space Black'),
  (5, 'MainFrameColour', 'J', 'Flamingo Pink'),
  (5, 'MainFrameColour', 'M', 'Metallic Green Gloss'),
  (5, 'MainFrameColour', 'D', 'Cobalt Blue Lacquer'),
  (5, 'MainFrameColour', 'H', 'Lavender Matt'),
  (5, 'MainFrameColour', 'L', 'Metallic Blue Gloss'),
  (5, 'MainFrameColour', 'U', 'Palm Green'),
  (5, 'MainFrameColour', 'Q', 'Wine Red Matt'),
  (5, 'MainFrameColour', 'C', 'Veligo Blue'),
  (5, 'MainFrameColour', '8', 'Purple Violet'),
  (5, 'MainFrameColour', 'P', 'Pale Brown'),
  (5, 'MainFrameColour', '7', 'Azure Blue'),
  (6, 'RearFrameColour', '1', 'Lunar Ice'),
  (6, 'RearFrameColour', '2', 'Cerakote Ti Black'),
  (6, 'RearFrameColour', '4', 'Forest Green'),
  (6, 'RearFrameColour', '5', 'Traildust White'),
  (6, 'RearFrameColour', '6', 'Adventure Orange'),
  (6, 'RearFrameColour', '9', 'Blasted Titanium'),
  (6, 'RearFrameColour', 'A', 'Bumblebee Yellow'),
  (6, 'RearFrameColour', 'B', 'Black - Matt'),
  (6, 'RearFrameColour', 'E', 'Ocean Blue'),
  (6, 'RearFrameColour', 'F', 'Amethyst Lacquer'),
  (6, 'RearFrameColour', 'G', 'Racing Green - Matt'),
  (6, 'RearFrameColour', 'K', 'Black Lacquer - Gloss'),
  (6, 'RearFrameColour', 'N', 'Dune Sand'),
  (6, 'RearFrameColour', 'O', 'Bottle Green'),
  (6, 'RearFrameColour', 'R', 'Turkish Green - Matt'),
  (6, 'RearFrameColour', 'V', 'Bolt Blue Lacquer'),
  (6, 'RearFrameColour', 'W', 'Yuzu Lime'),
  (6, 'RearFrameColour', 'X', 'Special Colour X'),
  (6, 'RearFrameColour', 'Y', 'Special Colour Y'),
  (6, 'RearFrameColour', 'Z', 'Special Colour Z'),
  (6, 'RearFrameColour', '3', 'Space Black'),
  (6, 'RearFrameColour', 'J', 'Flamingo Pink'),
  (6, 'RearFrameColour', 'M', 'Metallic Green Gloss'),
  (6, 'RearFrameColour', 'D', 'Cobalt Blue Lacquer'),
  (6, 'RearFrameColour', 'H', 'Lavender Matt'),
  (6, 'RearFrameColour', 'L', 'Metallic Blue Gloss'),
  (6, 'RearFrameColour', 'U', 'Palm Green'),
  (6, 'RearFrameColour', 'Q', 'Wine Red Matt'),
  (6, 'RearFrameColour', 'S', 'Gloss White'),
  (6, 'RearFrameColour', 'C', 'Veligo Blue'),
  (6, 'RearFrameColour', '8', 'Purple Violet'),
  (6, 'RearFrameColour', 'T', 'Midnight Black Metallic'),
  (6, 'RearFrameColour', 'P', 'Pale Brown'),
  (6, 'RearFrameColour', '7', 'Azure Blue'),
  (7, 'FrontCarrierBlock', '0', 'No front carrier block'),
  (7, 'FrontCarrierBlock', '1', 'Bomber Front End Carrier Block - Category Electric'),
  (7, 'FrontCarrierBlock', '2', 'forged front carrier block'),
  (7, 'FrontCarrierBlock', 'A', 'Front Carrier Block - Electric Brixton'),
  (7, 'FrontCarrierBlock', 'B', 'Front Carrier Block'),
  (7, 'FrontCarrierBlock', 'E', 'Front Carrier Block - Bromtpon Electric'),
  (7, 'FrontCarrierBlock', 'G', 'Front Carrier Block - B Electric Greenway'),
  (8, 'Lighting', '0', 'Refls only NO LIGHTS'),
  (8, 'Lighting', '1', 'Rechargeable Battery - Lezyne Hecto Drive 500 XL'),
  (8, 'Lighting', '2', 'Rechargeable Battery - Lezyne Hecto 40'),
  (8, 'Lighting', '3', 'New Brixton E-Bike Light'),
  (8, 'Lighting', 'B', 'BAT lamps Front and Rear'),
  (8, 'Lighting', 'C', 'B+M AVY Integrated Lights on Brompton Electric'),
  (8, 'Lighting', 'D', 'G Volt 60 Battery lamps Front and Rear'),
  (8, 'Lighting', 'E', 'Lezyne E115'),
  (8, 'Lighting', 'S', 'SP Hub Dynamo (SV-8)'),
  (9, 'SaddleHeight', '0', 'Standard seat post'),
  (9, 'SaddleHeight', '6', 'Extended seat post'),
  (9, 'SaddleHeight', 'A', 'Telescopic seat post'),
  (9, 'SaddleHeight', 'B', 'Superlight Standard'),
  (9, 'SaddleHeight', 'C', 'Superlight Extended'),
  (9, 'SaddleHeight', 'T', 'Superlight Telescopic'),
  (10, 'GearRatio', '0', 'Standard Gearing'),
  (10, 'GearRatio', 'A', '44T Chainring'),
  (10, 'GearRatio', 'B', '50T Chainring'),
  (10, 'GearRatio', 'C', '54T Chainring'),
  (10, 'GearRatio', 'D', '56T Chainring'),
  (10, 'GearRatio', 'I', 'Increased Gearing'),
  (10, 'GearRatio', 'R', 'Reduced Gearing'),
  (11, 'Saddle', '0', 'Saddle Standard'),
  (11, 'Saddle', '1', 'Custom Saddle'),
  (11, 'Saddle', '2', 'City + Comfy Saddle'),
  (11, 'Saddle', '3', 'Custom AndWander'),
  (11, 'Saddle', '4', 'Brooks B17 Green'),
  (11, 'Saddle', '5', 'Brooks C17 Barbour'),
  (11, 'Saddle', '6', 'Standard Custom'),
  (11, 'Saddle', '7', 'Fizik Aliante R7'),
  (11, 'Saddle', 'A', 'Brooks Cambium C17 All Weather'),
  (11, 'Saddle', 'B', 'Saddle Brooks B17 Special Men'),
  (11, 'Saddle', 'C', 'Saddle Brooks B17 Black Men'),
  (11, 'Saddle', 'D', 'A-Line Saddle'),
  (11, 'Saddle', 'F', 'Custom Saddle - P-TDF'),
  (11, 'Saddle', 'G', 'Custom Saddle - C-TDF'),
  (11, 'Saddle', 'H', 'Saddle Chateaux'),
  (11, 'Saddle', 'L', 'Saddle Brooks B17 Special Female'),
  (11, 'Saddle', 'O', 'Superlight Saddle'),
  (11, 'Saddle', 'Q', 'Saddle Brooks Cambium All Weather TeamGB'),
  (11, 'Saddle', 'T', 'Superlight Carbon Saddle'),
  (11, 'Saddle', 'U', 'Ultra Saddle With Titanium Rails CHPT3'),
  (11, 'Saddle', 'V', 'Custom Saddle - Velo White'),
  (11, 'Saddle', 'W', 'Saddle Standard Wide'),
  (11, 'Saddle', 'X', 'Fizik Terra Argo'),
  (12, 'Tyre', '0', 'Schwalbe Marathon Racer Tyre'),
  (12, 'Tyre', '1', 'Schwalbe ONE Tanwall Tyre'),
  (12, 'Tyre', '2', 'Schwalbe ONE Black Tyre'),
  (12, 'Tyre', '3', 'Conti Tyre Black/Tan 20in'),
  (12, 'Tyre', '4', 'Schwalbe Big Apple Black'),
  (12, 'Tyre', '5', 'Schwalbe Marathon Almotion'),
  (12, 'Tyre', '6', 'Custom AndWander'),
  (12, 'Tyre', 'A', 'A Line Schwalbe Marathon Racer'),
  (12, 'Tyre', 'C', 'Continental Contact Urban 16in'),
  (12, 'Tyre', 'D', 'CONTINENTAL CONTACT URBAN CREAM'),
  (12, 'Tyre', 'G', 'Schwalbe G-One All Round 54-406. Tan wall'),
  (12, 'Tyre', 'J', 'Schwalbe Kojak Tyre'),
  (12, 'Tyre', 'K', 'A Line Schwalbe Kojak Tyre'),
  (12, 'Tyre', 'M', 'Schwalbe Marathon Tyre'),
  (12, 'Tyre', 'R', 'Pirelli Angel RS Black Sidewall'),
  (12, 'Tyre', 'T', 'Marathon Tanwall (Folding) Tyre'),
  (13, 'Brakes', '0', 'Brakes FWD Orientation'),
  (13, 'Brakes', 'R', 'Brakes REV Orientation'),
  (14, 'Pedals', '0', 'Folding pedal LH & RH std'),
  (14, 'Pedals', 'N', 'No Folding pedal LH & RH std'),
  (14, 'Pedals', 'Q', 'Quick Release'),
  (15, 'Saddlebag', '0', 'Code Not in Use'),
  (15, 'Saddlebag', '1', 'Saddle bag Chateaux'),
  (15, 'Saddlebag', '2', 'Leather Saddle Roll Bag'),
  (16, 'Suspension', '0', 'Std Suspension pad WITH clip'),
  (16, 'Suspension', 'F', 'Firm Suspension pad with clip'),
  (16, 'Suspension', 'R', 'Red Xtra Firm Suspension Block - w/ clip'),
  (16, 'Suspension', 'W', 'White Suspension Block'),
  (17, 'BikeType', '0', 'C Line'),
  (17, 'BikeType', '1', 'C Line Demo'),
  (17, 'BikeType', '2', 'P Line BBC'),
  (17, 'BikeType', '4', 'C Line TeamGB Staff'),
  (17, 'BikeType', '5', 'C Line Barbour Edition'),
  (17, 'BikeType', '6', 'C Line Millionth Edition'),
  (17, 'BikeType', '7', 'NA Artist C Line'),
  (17, 'BikeType', '8', 'C Line TDF'),
  (17, 'BikeType', '9', 'C Line Classic Silver'),
  (17, 'BikeType', 'A', 'A Line'),
  (17, 'BikeType', 'B', 'C Line Black Edition'),
  (17, 'BikeType', 'E', 'C Line Electric'),
  (17, 'BikeType', 'F', 'C Line Electric Demo'),
  (17, 'BikeType', 'G', 'G Line'),
  (17, 'BikeType', 'H', 'G Line Electric'),
  (17, 'BikeType', 'I', 'P Line'),
  (17, 'BikeType', 'J', 'P Line Electric'),
  (17, 'BikeType', 'K', 'P Line Demo'),
  (17, 'BikeType', 'L', 'P Line Shenzhen Junction'),
  (17, 'BikeType', 'M', 'P Line Electric Demo'),
  (17, 'BikeType', 'N', 'C Line Nickel'),
  (17, 'BikeType', 'O', 'C Line Team GB Edition'),
  (17, 'BikeType', 'R', 'C Line Beyond Edition'),
  (17, 'BikeType', 'S', 'G Line Electric Demo'),
  (17, 'BikeType', 'T', 'T Line'),
  (17, 'BikeType', 'V', 'T Line Demo'),
  (17, 'BikeType', 'W', 'G Line Demo'),
  (17, 'BikeType', 'X', 'Special Colour BED'),
  (17, 'BikeType', 'Y', 'C Line 50th Anniversary'),
  (17, 'BikeType', '3', 'C Line Electric MK6'),
  (17, 'BikeType', 'D', 'C Line Electric Brixton'),
  (17, 'BikeType', 'U', 'T Line Electric'),
  (17, 'BikeType', 'C', 'C Line MK6'),
  (17, 'BikeType', 'Q', 'P Line Electric Brixton'),
  (17, 'BikeType', 'P', 'P Line'),
  (18, 'Toolkit', '0', 'Code Not in Use'),
  (18, 'Toolkit', '1', 'Brompton Toolkit'),
  (19, 'SaddleLight', '0', 'Code Not in Use'),
  (20, 'ConfigurationCode', '1', 'MY20'),
  (20, 'ConfigurationCode', '2', 'MY21'),
  (20, 'ConfigurationCode', '3', 'MY22'),
  (20, 'ConfigurationCode', '4', 'MY23'),
  (20, 'ConfigurationCode', '5', 'MY24'),
  (20, 'ConfigurationCode', '6', 'MY25 Version'),
  (20, 'ConfigurationCode', '7', 'MY26 Version'),
  (21, 'OptionsBox(Electriconly)', '0', 'None'),
  (21, 'OptionsBox(Electriconly)', '1', 'Option Box 1 - Bag - Charger - UK Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', '2', 'Option Box 2 - Batt-Bag-Charger-UK Plug & Man'),
  (21, 'OptionsBox(Electriconly)', '3', 'Option Box 3 - Bag - Charger - EU Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', '4', 'Option Box 4 - Batt,Bag-Charger-EU Plug & Man'),
  (21, 'OptionsBox(Electriconly)', '5', 'Option Box 5 - Bag - Charger - US Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', '6', 'Option Box 6 - Batt-Bag-Charger-US Plug & Man'),
  (21, 'OptionsBox(Electriconly)', '7', 'Option Box 7 - Manual Only'),
  (21, 'OptionsBox(Electriconly)', '8', 'Option Box 8 - Bag - Charger - AU Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', '9', 'Option Box 9 - Batt-Bag-Charger-AU Plug & Man'),
  (21, 'OptionsBox(Electriconly)', 'A', 'Option Box A - Bag - Charger - US Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', 'B', 'Option Box 12 - Batt-Bag-Charger-US Plug & Man'),
  (21, 'OptionsBox(Electriconly)', 'E', 'GE Line Greenway Battery, Small bag, 2A charger UK.'),
  (21, 'OptionsBox(Electriconly)', 'F', 'GE Line Greenway Battery, Small bag, 2A charger EU.'),
  (21, 'OptionsBox(Electriconly)', 'G', 'GE Line Greenway Battery, Small bag, 2A charger US.'),
  (21, 'OptionsBox(Electriconly)', 'H', 'GE Line Greenway Battery, Small bag, 2A charger AU/NZ.'),
  (22, 'FrameMaterial', 'T', 'All Titanium - Mk6 Extremities'),
  (22, 'FrameSet', '1', 'Standard'),
  (22, 'FrameSet', '2', 'Demo'),
  (22, 'FrameSet', '3', 'Special NA Artist V2'),
  (22, 'FrameSet', '4', 'Special Comfort(City+)'),
  (22, 'FrameSet', '5', 'Special Veligo'),
  (22, 'FrameSet', '6', 'APAC Urban Outdoor'),
  (22, 'FrameSet', '7', 'APAC Premium Silver'),
  (22, 'FrameSet', '8', 'Freelander'),
  (22, 'FrameSet', '9', 'Vitality'),
  (23, 'ComponentColour', '1', 'Silver'),
  (23, 'ComponentColour', '2', 'Black'),
  (24, 'OnBikeAccessories', '0', 'None'),
  (24, 'OnBikeAccessories', '5', 'Lezyne Pump and Mounts'),
  (24, 'OnBikeAccessories', 'A', 'DTH Kit'),
  (24, 'OnBikeAccessories', 'B', 'DTH Kit FR Reg'),
  (24, 'OnBikeAccessories', 'C', 'DTH Kit & Lezyne Pump and Mounts'),
  (24, 'OnBikeAccessories', 'D', 'DTH Kit FR Reg & Lezyne Pump and Mounts'),
  (24, 'OnBikeAccessories', 'E', 'DTH Kit A-Line & Zefal Brompton Pump'),
  (24, 'OnBikeAccessories', 'F', 'DTH Kit A-Line FR Reg & Zefal Brompton Pump'),
  (24, 'OnBikeAccessories', 'G', 'DTH Kit A-Line'),
  (24, 'OnBikeAccessories', 'H', 'DTH Kit A-Line FR Reg'),
  (24, 'OnBikeAccessories', 'M', 'Flexi Mudguard'),
  (24, 'OnBikeAccessories', 'S', 'Lezyne Pump Silver'),
  (24, 'OnBikeAccessories', 'Z', 'Zefal Brompton Pump'),
  (25, 'HandlebarStemColour', '1', 'Lunar Ice'),
  (25, 'HandlebarStemColour', '2', 'Cerakote Ti Black'),
  (25, 'HandlebarStemColour', '3', 'Pure Orange Matt'),
  (25, 'HandlebarStemColour', '4', 'Forest Green'),
  (25, 'HandlebarStemColour', '5', 'Baby Pink'),
  (25, 'HandlebarStemColour', '6', 'Tempest Blue'),
  (25, 'HandlebarStemColour', '8', 'Pall Mall White Gloss'),
  (25, 'HandlebarStemColour', '9', 'Blasted Titanium'),
  (25, 'HandlebarStemColour', 'A', 'Bumblebee Yellow'),
  (25, 'HandlebarStemColour', 'B', 'Black - Matt'),
  (25, 'HandlebarStemColour', 'D', 'Oxblood Red Gloss'),
  (25, 'HandlebarStemColour', 'E', 'Ocean Blue'),
  (25, 'HandlebarStemColour', 'F', 'Amethyst Lacquer'),
  (25, 'HandlebarStemColour', 'G', 'Racing Green - Matt'),
  (25, 'HandlebarStemColour', 'K', 'Black Lacquer - Gloss'),
  (25, 'HandlebarStemColour', 'M', 'Bronze Sky Metallic'),
  (25, 'HandlebarStemColour', 'N', 'Dune Sand'),
  (25, 'HandlebarStemColour', 'O', 'Bottle Green'),
  (25, 'HandlebarStemColour', 'R', 'Turkish Green - Matt'),
  (25, 'HandlebarStemColour', 'S', 'Papyrus White - Matt'),
  (25, 'HandlebarStemColour', 'T', 'Midnight Black Metallic'),
  (25, 'HandlebarStemColour', 'V', 'Bolt Blue Lacquer'),
  (25, 'HandlebarStemColour', 'W', 'Yuzu Lime'),
  (25, 'HandlebarStemColour', 'X', 'Special Colour X'),
  (25, 'HandlebarStemColour', 'Y', 'Special Colour Y'),
  (25, 'HandlebarStemColour', 'Z', 'Special Colour Z'),
  (25, 'HandlebarStemColour', 'J', 'Flamingo Pink'),
  (25, 'HandlebarStemColour', 'H', 'Lavender Matt'),
  (25, 'HandlebarStemColour', 'L', 'Metallic Blue Gloss'),
  (25, 'HandlebarStemColour', 'U', 'Palm Green'),
  (25, 'HandlebarStemColour', 'Q', 'Wine Red Matt'),
  (25, 'HandlebarStemColour', 'C', 'Veligo Blue'),
  (25, 'HandlebarStemColour', 'P', 'Pale Brown'),
  (25, 'HandlebarStemColour', '7', 'Azure Blue'),
  (26, 'HandlebarPinColour', '1', 'Lunar Ice'),
  (26, 'HandlebarPinColour', '2', 'Yellow Gloss'),
  (26, 'HandlebarPinColour', '3', 'Pure Orange Matt'),
  (26, 'HandlebarPinColour', '4', 'White - Gloss'),
  (26, 'HandlebarPinColour', '5', 'Baby Pink'),
  (26, 'HandlebarPinColour', '6', 'Tempest Blue'),
  (26, 'HandlebarPinColour', '7', 'Laurel Green Gloss'),
  (26, 'HandlebarPinColour', '9', 'Blasted Ti'),
  (26, 'HandlebarPinColour', 'A', 'Bumblebee Yellow'),
  (26, 'HandlebarPinColour', 'B', 'Black - Matt'),
  (26, 'HandlebarPinColour', 'D', 'Oxblood Red Gloss'),
  (26, 'HandlebarPinColour', 'E', 'Ocean Blue'),
  (26, 'HandlebarPinColour', 'F', 'Amethyst Lacquer'),
  (26, 'HandlebarPinColour', 'G', 'Racing Green - Matt'),
  (26, 'HandlebarPinColour', 'K', 'Black Lacquer - Gloss'),
  (26, 'HandlebarPinColour', 'M', 'Bronze Sky Metallic'),
  (26, 'HandlebarPinColour', 'N', 'Dune Sand'),
  (26, 'HandlebarPinColour', 'O', 'Bottle Green'),
  (26, 'HandlebarPinColour', 'R', 'Turkish Green - Matt'),
  (26, 'HandlebarPinColour', 'T', 'Midnight Black Metallic'),
  (26, 'HandlebarPinColour', 'V', 'Bolt Blue Lacquer'),
  (26, 'HandlebarPinColour', 'W', 'Sulphur Yellow'),
  (26, 'HandlebarPinColour', 'X', 'Special Colour X'),
  (26, 'HandlebarPinColour', 'Y', 'Special Colour Y'),
  (26, 'HandlebarPinColour', 'Z', 'Special Colour Z'),
  (26, 'HandlebarPinColour', 'J', 'Flamingo Pink'),
  (26, 'HandlebarPinColour', 'S', 'Gloss White'),
  (26, 'HandlebarPinColour', 'H', 'Lavender Matt'),
  (26, 'HandlebarPinColour', 'L', 'Metallic Blue Gloss'),
  (26, 'HandlebarPinColour', 'U', 'Palm Green'),
  (26, 'HandlebarPinColour', 'Q', 'Wine Red Matt'),
  (26, 'HandlebarPinColour', 'C', 'Veligo Blue'),
  (26, 'HandlebarPinColour', 'P', 'Pale Brown'),
  (26, 'HandlebarPinColour', '8', 'Purple Violet'),
  (27, 'FrontFrameColour', '1', 'Lunar Ice'),
  (27, 'FrontFrameColour', '4', 'Forest Green'),
  (27, 'FrontFrameColour', '5', 'Traildust White'),
  (27, 'FrontFrameColour', '6', 'Adventure Orange'),
  (27, 'FrontFrameColour', '7', 'Laurel Green Gloss'),
  (27, 'FrontFrameColour', '9', 'Blasted Ti'),
  (27, 'FrontFrameColour', 'B', 'Black - Matt'),
  (27, 'FrontFrameColour', 'C', 'Cerakote Ti Red'),
  (27, 'FrontFrameColour', 'F', 'Amethyst Lacquer'),
  (27, 'FrontFrameColour', 'G', 'Racing Green - Matt'),
  (27, 'FrontFrameColour', 'K', 'Black Lacquer - Gloss'),
  (27, 'FrontFrameColour', 'N', 'Dune Sand'),
  (27, 'FrontFrameColour', 'O', 'Bottle Green'),
  (27, 'FrontFrameColour', 'R', 'Turkish Green - Matt'),
  (27, 'FrontFrameColour', 'S', 'Papyrus White - Matt'),
  (27, 'FrontFrameColour', 'T', 'Midnight Black Metallic'),
  (27, 'FrontFrameColour', 'V', 'Bolt Blue Lacquer'),
  (27, 'FrontFrameColour', 'W', 'Sulphur Yellow'),
  (27, 'FrontFrameColour', 'X', 'Special Colour X'),
  (27, 'FrontFrameColour', 'Y', 'Special Colour Y'),
  (27, 'FrontFrameColour', 'Z', 'Special Colour Z'),
  (27, 'FrontFrameColour', '3', 'Space Black'),
  (27, 'FrontFrameColour', 'J', 'Flamingo Pink'),
  (27, 'FrontFrameColour', 'M', 'Metallic Green Gloss'),
  (27, 'FrontFrameColour', 'D', 'Cobalt Blue Lacquer'),
  (27, 'FrontFrameColour', 'H', 'Lavender Matt'),
  (27, 'FrontFrameColour', 'L', 'Metallic Blue Gloss'),
  (27, 'FrontFrameColour', 'U', 'Palm Green'),
  (27, 'FrontFrameColour', 'Q', 'Wine Red Matt'),
  (27, 'FrontFrameColour', '2', 'Beige Grey'),
  (27, 'FrontFrameColour', 'A', 'Pastel Violet'),
  (27, 'FrontFrameColour', 'P', 'Pale Brown'),
  (27, 'FrontFrameColour', '8', 'Purple Violet'),
  (27, 'FrontFrameColour', 'E', 'Vitality Pink'),
  (28, 'FrontForkColour', '1', 'Lunar Ice'),
  (28, 'FrontForkColour', '2', 'Yellow Gloss'),
  (28, 'FrontForkColour', '4', 'Forest Green'),
  (28, 'FrontForkColour', '5', 'Traildust White'),
  (28, 'FrontForkColour', '6', 'Adventure Orange'),
  (28, 'FrontForkColour', '7', 'Laurel Green Gloss'),
  (28, 'FrontForkColour', '9', 'Blasted Titanium'),
  (28, 'FrontForkColour', 'A', 'Bumblebee Yellow'),
  (28, 'FrontForkColour', 'B', 'Black - Matt'),
  (28, 'FrontForkColour', 'D', 'Oxblood Red Gloss'),
  (28, 'FrontForkColour', 'E', 'Ocean Blue'),
  (28, 'FrontForkColour', 'F', 'Amethyst Lacquer'),
  (28, 'FrontForkColour', 'G', 'Racing Green - Matt'),
  (28, 'FrontForkColour', 'K', 'Black Lacquer - Gloss'),
  (28, 'FrontForkColour', 'M', 'Bronze Sky Metallic'),
  (28, 'FrontForkColour', 'N', 'Dune Sand'),
  (28, 'FrontForkColour', 'O', 'Bottle Green'),
  (28, 'FrontForkColour', 'R', 'Turkish Green - Matt'),
  (28, 'FrontForkColour', 'S', 'Papyrus White - Matt'),
  (28, 'FrontForkColour', 'T', 'Midnight Black Metallic'),
  (28, 'FrontForkColour', 'V', 'Bolt Blue Lacquer'),
  (28, 'FrontForkColour', 'W', 'Sulphur Yellow'),
  (28, 'FrontForkColour', 'X', 'Special Colour X'),
  (28, 'FrontForkColour', 'Y', 'Special Colour Y'),
  (28, 'FrontForkColour', 'Z', 'Special Colour Z'),
  (28, 'FrontForkColour', '3', 'Space Black'),
  (28, 'FrontForkColour', 'J', 'Flamingo Pink'),
  (28, 'FrontForkColour', 'H', 'Lavender Matt'),
  (28, 'FrontForkColour', 'L', 'Piccadilly Blue'),
  (28, 'FrontForkColour', 'U', 'Palm Green'),
  (28, 'FrontForkColour', 'Q', 'Wine Red Matt'),
  (28, 'FrontForkColour', 'C', 'Veligo Blue'),
  (28, 'FrontForkColour', 'P', 'Pale Brown'),
  (28, 'FrontForkColour', '8', 'Purple Violet'),
  (29, 'Position29', '1', 'Code 1'),
  (30, 'Grade', '0', 'New'),
  (30, 'Grade', 'A', 'Grade A'),
  (30, 'Grade', 'B', 'Grade B'),
  (30, 'Grade', 'C', 'Grade C')
), seed as ( select digit_position, option_name, upper(code_value) as code_value, choice_value from seed_raw )
insert into sku_rules (digit_position, option_name, code_value, choice_value, description_element, is_active)
select s.digit_position, s.option_name, s.code_value, s.choice_value, s.choice_value, true from seed s
where not exists (select 1 from sku_rules r where r.is_active = true and ((s.digit_position > 0 and r.digit_position = s.digit_position and upper(r.code_value) = s.code_value) or (s.digit_position = 0 and r.digit_position = 0 and lower(r.option_name) = lower(s.option_name) and upper(r.code_value) = s.code_value)));
with seed_raw(digit_position, option_name, code_value, choice_value) as ( values
  (1, 'HandlebarType', '1', 'Small'),
  (1, 'HandlebarType', '2', 'Medium'),
  (1, 'HandlebarType', '3', 'Large'),
  (1, 'HandlebarType', 'A', 'A Line'),
  (1, 'HandlebarType', 'H', 'High'),
  (1, 'HandlebarType', 'M', 'Mid'),
  (1, 'HandlebarType', 'S', 'Low'),
  (2, 'Speeds', '1', 'One - 1 Speed'),
  (2, 'Speeds', '2', 'Urban - 2 Speeds'),
  (2, 'Speeds', '3', 'Utility - 3 Speeds'),
  (2, 'Speeds', '4', 'Urban - 4 Speeds'),
  (2, 'Speeds', '6', 'Explore - 6 Speeds'),
  (2, 'Speeds', '8', 'TBC - 8 Speeds'),
  (2, 'Speeds', 'L', 'Explore - 12 Speeds'),
  (3, 'MudguardsAndRack', 'E', 'No Mudguards - E-Version'),
  (3, 'MudguardsAndRack', 'L', 'Mudguards - L-Version'),
  (3, 'MudguardsAndRack', 'R', 'Mudguards and Rack - R-Version'),
  (4, 'Territory', '0', 'Code Not in Use'),
  (5, 'MainFrameColour', '1', 'Lunar Ice'),
  (5, 'MainFrameColour', '2', 'Cerakote Ti Black'),
  (5, 'MainFrameColour', '4', 'Forest Green'),
  (5, 'MainFrameColour', '5', 'Traildust White'),
  (5, 'MainFrameColour', '6', 'Adventure Orange'),
  (5, 'MainFrameColour', '9', 'Blasted Ti'),
  (5, 'MainFrameColour', 'A', 'Bumblebee Yellow'),
  (5, 'MainFrameColour', 'B', 'Black - Matt'),
  (5, 'MainFrameColour', 'E', 'Ocean Blue'),
  (5, 'MainFrameColour', 'F', 'Amethyst Lacquer'),
  (5, 'MainFrameColour', 'G', 'Racing Green - Matt'),
  (5, 'MainFrameColour', 'K', 'Black Lacquer - Gloss'),
  (5, 'MainFrameColour', 'N', 'Dune Sand'),
  (5, 'MainFrameColour', 'O', 'Bottle Green'),
  (5, 'MainFrameColour', 'R', 'Turkish Green - Matt'),
  (5, 'MainFrameColour', 'S', 'Papyrus White - Matt'),
  (5, 'MainFrameColour', 'T', 'Midnight Black Metallic'),
  (5, 'MainFrameColour', 'V', 'Bolt Blue Lacquer'),
  (5, 'MainFrameColour', 'W', 'Yuzu Lime'),
  (5, 'MainFrameColour', 'X', 'Special Colour X'),
  (5, 'MainFrameColour', 'Y', 'Special Colour Y'),
  (5, 'MainFrameColour', 'Z', 'Special Colour Z'),
  (5, 'MainFrameColour', '3', 'Space Black'),
  (5, 'MainFrameColour', 'J', 'Flamingo Pink'),
  (5, 'MainFrameColour', 'M', 'Metallic Green Gloss'),
  (5, 'MainFrameColour', 'D', 'Cobalt Blue Lacquer'),
  (5, 'MainFrameColour', 'H', 'Lavender Matt'),
  (5, 'MainFrameColour', 'L', 'Metallic Blue Gloss'),
  (5, 'MainFrameColour', 'U', 'Palm Green'),
  (5, 'MainFrameColour', 'Q', 'Wine Red Matt'),
  (5, 'MainFrameColour', 'C', 'Veligo Blue'),
  (5, 'MainFrameColour', '8', 'Purple Violet'),
  (5, 'MainFrameColour', 'P', 'Pale Brown'),
  (5, 'MainFrameColour', '7', 'Azure Blue'),
  (6, 'RearFrameColour', '1', 'Lunar Ice'),
  (6, 'RearFrameColour', '2', 'Cerakote Ti Black'),
  (6, 'RearFrameColour', '4', 'Forest Green'),
  (6, 'RearFrameColour', '5', 'Traildust White'),
  (6, 'RearFrameColour', '6', 'Adventure Orange'),
  (6, 'RearFrameColour', '9', 'Blasted Titanium'),
  (6, 'RearFrameColour', 'A', 'Bumblebee Yellow'),
  (6, 'RearFrameColour', 'B', 'Black - Matt'),
  (6, 'RearFrameColour', 'E', 'Ocean Blue'),
  (6, 'RearFrameColour', 'F', 'Amethyst Lacquer'),
  (6, 'RearFrameColour', 'G', 'Racing Green - Matt'),
  (6, 'RearFrameColour', 'K', 'Black Lacquer - Gloss'),
  (6, 'RearFrameColour', 'N', 'Dune Sand'),
  (6, 'RearFrameColour', 'O', 'Bottle Green'),
  (6, 'RearFrameColour', 'R', 'Turkish Green - Matt'),
  (6, 'RearFrameColour', 'V', 'Bolt Blue Lacquer'),
  (6, 'RearFrameColour', 'W', 'Yuzu Lime'),
  (6, 'RearFrameColour', 'X', 'Special Colour X'),
  (6, 'RearFrameColour', 'Y', 'Special Colour Y'),
  (6, 'RearFrameColour', 'Z', 'Special Colour Z'),
  (6, 'RearFrameColour', '3', 'Space Black'),
  (6, 'RearFrameColour', 'J', 'Flamingo Pink'),
  (6, 'RearFrameColour', 'M', 'Metallic Green Gloss'),
  (6, 'RearFrameColour', 'D', 'Cobalt Blue Lacquer'),
  (6, 'RearFrameColour', 'H', 'Lavender Matt'),
  (6, 'RearFrameColour', 'L', 'Metallic Blue Gloss'),
  (6, 'RearFrameColour', 'U', 'Palm Green'),
  (6, 'RearFrameColour', 'Q', 'Wine Red Matt'),
  (6, 'RearFrameColour', 'S', 'Gloss White'),
  (6, 'RearFrameColour', 'C', 'Veligo Blue'),
  (6, 'RearFrameColour', '8', 'Purple Violet'),
  (6, 'RearFrameColour', 'T', 'Midnight Black Metallic'),
  (6, 'RearFrameColour', 'P', 'Pale Brown'),
  (6, 'RearFrameColour', '7', 'Azure Blue'),
  (7, 'FrontCarrierBlock', '0', 'No front carrier block'),
  (7, 'FrontCarrierBlock', '1', 'Bomber Front End Carrier Block - Category Electric'),
  (7, 'FrontCarrierBlock', '2', 'forged front carrier block'),
  (7, 'FrontCarrierBlock', 'A', 'Front Carrier Block - Electric Brixton'),
  (7, 'FrontCarrierBlock', 'B', 'Front Carrier Block'),
  (7, 'FrontCarrierBlock', 'E', 'Front Carrier Block - Bromtpon Electric'),
  (7, 'FrontCarrierBlock', 'G', 'Front Carrier Block - B Electric Greenway'),
  (8, 'Lighting', '0', 'Refls only NO LIGHTS'),
  (8, 'Lighting', '1', 'Rechargeable Battery - Lezyne Hecto Drive 500 XL'),
  (8, 'Lighting', '2', 'Rechargeable Battery - Lezyne Hecto 40'),
  (8, 'Lighting', '3', 'New Brixton E-Bike Light'),
  (8, 'Lighting', 'B', 'BAT lamps Front and Rear'),
  (8, 'Lighting', 'C', 'B+M AVY Integrated Lights on Brompton Electric'),
  (8, 'Lighting', 'D', 'G Volt 60 Battery lamps Front and Rear'),
  (8, 'Lighting', 'E', 'Lezyne E115'),
  (8, 'Lighting', 'S', 'SP Hub Dynamo (SV-8)'),
  (9, 'SaddleHeight', '0', 'Standard seat post'),
  (9, 'SaddleHeight', '6', 'Extended seat post'),
  (9, 'SaddleHeight', 'A', 'Telescopic seat post'),
  (9, 'SaddleHeight', 'B', 'Superlight Standard'),
  (9, 'SaddleHeight', 'C', 'Superlight Extended'),
  (9, 'SaddleHeight', 'T', 'Superlight Telescopic'),
  (10, 'GearRatio', '0', 'Standard Gearing'),
  (10, 'GearRatio', 'A', '44T Chainring'),
  (10, 'GearRatio', 'B', '50T Chainring'),
  (10, 'GearRatio', 'C', '54T Chainring'),
  (10, 'GearRatio', 'D', '56T Chainring'),
  (10, 'GearRatio', 'I', 'Increased Gearing'),
  (10, 'GearRatio', 'R', 'Reduced Gearing'),
  (11, 'Saddle', '0', 'Saddle Standard'),
  (11, 'Saddle', '1', 'Custom Saddle'),
  (11, 'Saddle', '2', 'City + Comfy Saddle'),
  (11, 'Saddle', '3', 'Custom AndWander'),
  (11, 'Saddle', '4', 'Brooks B17 Green'),
  (11, 'Saddle', '5', 'Brooks C17 Barbour'),
  (11, 'Saddle', '6', 'Standard Custom'),
  (11, 'Saddle', '7', 'Fizik Aliante R7'),
  (11, 'Saddle', 'A', 'Brooks Cambium C17 All Weather'),
  (11, 'Saddle', 'B', 'Saddle Brooks B17 Special Men'),
  (11, 'Saddle', 'C', 'Saddle Brooks B17 Black Men'),
  (11, 'Saddle', 'D', 'A-Line Saddle'),
  (11, 'Saddle', 'F', 'Custom Saddle - P-TDF'),
  (11, 'Saddle', 'G', 'Custom Saddle - C-TDF'),
  (11, 'Saddle', 'H', 'Saddle Chateaux'),
  (11, 'Saddle', 'L', 'Saddle Brooks B17 Special Female'),
  (11, 'Saddle', 'O', 'Superlight Saddle'),
  (11, 'Saddle', 'Q', 'Saddle Brooks Cambium All Weather TeamGB'),
  (11, 'Saddle', 'T', 'Superlight Carbon Saddle'),
  (11, 'Saddle', 'U', 'Ultra Saddle With Titanium Rails CHPT3'),
  (11, 'Saddle', 'V', 'Custom Saddle - Velo White'),
  (11, 'Saddle', 'W', 'Saddle Standard Wide'),
  (11, 'Saddle', 'X', 'Fizik Terra Argo'),
  (12, 'Tyre', '0', 'Schwalbe Marathon Racer Tyre'),
  (12, 'Tyre', '1', 'Schwalbe ONE Tanwall Tyre'),
  (12, 'Tyre', '2', 'Schwalbe ONE Black Tyre'),
  (12, 'Tyre', '3', 'Conti Tyre Black/Tan 20in'),
  (12, 'Tyre', '4', 'Schwalbe Big Apple Black'),
  (12, 'Tyre', '5', 'Schwalbe Marathon Almotion'),
  (12, 'Tyre', '6', 'Custom AndWander'),
  (12, 'Tyre', 'A', 'A Line Schwalbe Marathon Racer'),
  (12, 'Tyre', 'C', 'Continental Contact Urban 16in'),
  (12, 'Tyre', 'D', 'CONTINENTAL CONTACT URBAN CREAM'),
  (12, 'Tyre', 'G', 'Schwalbe G-One All Round 54-406. Tan wall'),
  (12, 'Tyre', 'J', 'Schwalbe Kojak Tyre'),
  (12, 'Tyre', 'K', 'A Line Schwalbe Kojak Tyre'),
  (12, 'Tyre', 'M', 'Schwalbe Marathon Tyre'),
  (12, 'Tyre', 'R', 'Pirelli Angel RS Black Sidewall'),
  (12, 'Tyre', 'T', 'Marathon Tanwall (Folding) Tyre'),
  (13, 'Brakes', '0', 'Brakes FWD Orientation'),
  (13, 'Brakes', 'R', 'Brakes REV Orientation'),
  (14, 'Pedals', '0', 'Folding pedal LH & RH std'),
  (14, 'Pedals', 'N', 'No Folding pedal LH & RH std'),
  (14, 'Pedals', 'Q', 'Quick Release'),
  (15, 'Saddlebag', '0', 'Code Not in Use'),
  (15, 'Saddlebag', '1', 'Saddle bag Chateaux'),
  (15, 'Saddlebag', '2', 'Leather Saddle Roll Bag'),
  (16, 'Suspension', '0', 'Std Suspension pad WITH clip'),
  (16, 'Suspension', 'F', 'Firm Suspension pad with clip'),
  (16, 'Suspension', 'R', 'Red Xtra Firm Suspension Block - w/ clip'),
  (16, 'Suspension', 'W', 'White Suspension Block'),
  (17, 'BikeType', '0', 'C Line'),
  (17, 'BikeType', '1', 'C Line Demo'),
  (17, 'BikeType', '2', 'P Line BBC'),
  (17, 'BikeType', '4', 'C Line TeamGB Staff'),
  (17, 'BikeType', '5', 'C Line Barbour Edition'),
  (17, 'BikeType', '6', 'C Line Millionth Edition'),
  (17, 'BikeType', '7', 'NA Artist C Line'),
  (17, 'BikeType', '8', 'C Line TDF'),
  (17, 'BikeType', '9', 'C Line Classic Silver'),
  (17, 'BikeType', 'A', 'A Line'),
  (17, 'BikeType', 'B', 'C Line Black Edition'),
  (17, 'BikeType', 'E', 'C Line Electric'),
  (17, 'BikeType', 'F', 'C Line Electric Demo'),
  (17, 'BikeType', 'G', 'G Line'),
  (17, 'BikeType', 'H', 'G Line Electric'),
  (17, 'BikeType', 'I', 'P Line'),
  (17, 'BikeType', 'J', 'P Line Electric'),
  (17, 'BikeType', 'K', 'P Line Demo'),
  (17, 'BikeType', 'L', 'P Line Shenzhen Junction'),
  (17, 'BikeType', 'M', 'P Line Electric Demo'),
  (17, 'BikeType', 'N', 'C Line Nickel'),
  (17, 'BikeType', 'O', 'C Line Team GB Edition'),
  (17, 'BikeType', 'R', 'C Line Beyond Edition'),
  (17, 'BikeType', 'S', 'G Line Electric Demo'),
  (17, 'BikeType', 'T', 'T Line'),
  (17, 'BikeType', 'V', 'T Line Demo'),
  (17, 'BikeType', 'W', 'G Line Demo'),
  (17, 'BikeType', 'X', 'Special Colour BED'),
  (17, 'BikeType', 'Y', 'C Line 50th Anniversary'),
  (17, 'BikeType', '3', 'C Line Electric MK6'),
  (17, 'BikeType', 'D', 'C Line Electric Brixton'),
  (17, 'BikeType', 'U', 'T Line Electric'),
  (17, 'BikeType', 'C', 'C Line MK6'),
  (17, 'BikeType', 'Q', 'P Line Electric Brixton'),
  (17, 'BikeType', 'P', 'P Line'),
  (18, 'Toolkit', '0', 'Code Not in Use'),
  (18, 'Toolkit', '1', 'Brompton Toolkit'),
  (19, 'SaddleLight', '0', 'Code Not in Use'),
  (20, 'ConfigurationCode', '1', 'MY20'),
  (20, 'ConfigurationCode', '2', 'MY21'),
  (20, 'ConfigurationCode', '3', 'MY22'),
  (20, 'ConfigurationCode', '4', 'MY23'),
  (20, 'ConfigurationCode', '5', 'MY24'),
  (20, 'ConfigurationCode', '6', 'MY25 Version'),
  (20, 'ConfigurationCode', '7', 'MY26 Version'),
  (21, 'OptionsBox(Electriconly)', '0', 'None'),
  (21, 'OptionsBox(Electriconly)', '1', 'Option Box 1 - Bag - Charger - UK Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', '2', 'Option Box 2 - Batt-Bag-Charger-UK Plug & Man'),
  (21, 'OptionsBox(Electriconly)', '3', 'Option Box 3 - Bag - Charger - EU Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', '4', 'Option Box 4 - Batt,Bag-Charger-EU Plug & Man'),
  (21, 'OptionsBox(Electriconly)', '5', 'Option Box 5 - Bag - Charger - US Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', '6', 'Option Box 6 - Batt-Bag-Charger-US Plug & Man'),
  (21, 'OptionsBox(Electriconly)', '7', 'Option Box 7 - Manual Only'),
  (21, 'OptionsBox(Electriconly)', '8', 'Option Box 8 - Bag - Charger - AU Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', '9', 'Option Box 9 - Batt-Bag-Charger-AU Plug & Man'),
  (21, 'OptionsBox(Electriconly)', 'A', 'Option Box A - Bag - Charger - US Plug & Manuals'),
  (21, 'OptionsBox(Electriconly)', 'B', 'Option Box 12 - Batt-Bag-Charger-US Plug & Man'),
  (21, 'OptionsBox(Electriconly)', 'E', 'GE Line Greenway Battery, Small bag, 2A charger UK.'),
  (21, 'OptionsBox(Electriconly)', 'F', 'GE Line Greenway Battery, Small bag, 2A charger EU.'),
  (21, 'OptionsBox(Electriconly)', 'G', 'GE Line Greenway Battery, Small bag, 2A charger US.'),
  (21, 'OptionsBox(Electriconly)', 'H', 'GE Line Greenway Battery, Small bag, 2A charger AU/NZ.'),
  (22, 'FrameMaterial', 'T', 'All Titanium - Mk6 Extremities'),
  (22, 'FrameSet', '1', 'Standard'),
  (22, 'FrameSet', '2', 'Demo'),
  (22, 'FrameSet', '3', 'Special NA Artist V2'),
  (22, 'FrameSet', '4', 'Special Comfort(City+)'),
  (22, 'FrameSet', '5', 'Special Veligo'),
  (22, 'FrameSet', '6', 'APAC Urban Outdoor'),
  (22, 'FrameSet', '7', 'APAC Premium Silver'),
  (22, 'FrameSet', '8', 'Freelander'),
  (22, 'FrameSet', '9', 'Vitality'),
  (23, 'ComponentColour', '1', 'Silver'),
  (23, 'ComponentColour', '2', 'Black'),
  (24, 'OnBikeAccessories', '0', 'None'),
  (24, 'OnBikeAccessories', '5', 'Lezyne Pump and Mounts'),
  (24, 'OnBikeAccessories', 'A', 'DTH Kit'),
  (24, 'OnBikeAccessories', 'B', 'DTH Kit FR Reg'),
  (24, 'OnBikeAccessories', 'C', 'DTH Kit & Lezyne Pump and Mounts'),
  (24, 'OnBikeAccessories', 'D', 'DTH Kit FR Reg & Lezyne Pump and Mounts'),
  (24, 'OnBikeAccessories', 'E', 'DTH Kit A-Line & Zefal Brompton Pump'),
  (24, 'OnBikeAccessories', 'F', 'DTH Kit A-Line FR Reg & Zefal Brompton Pump'),
  (24, 'OnBikeAccessories', 'G', 'DTH Kit A-Line'),
  (24, 'OnBikeAccessories', 'H', 'DTH Kit A-Line FR Reg'),
  (24, 'OnBikeAccessories', 'M', 'Flexi Mudguard'),
  (24, 'OnBikeAccessories', 'S', 'Lezyne Pump Silver'),
  (24, 'OnBikeAccessories', 'Z', 'Zefal Brompton Pump'),
  (25, 'HandlebarStemColour', '1', 'Lunar Ice'),
  (25, 'HandlebarStemColour', '2', 'Cerakote Ti Black'),
  (25, 'HandlebarStemColour', '3', 'Pure Orange Matt'),
  (25, 'HandlebarStemColour', '4', 'Forest Green'),
  (25, 'HandlebarStemColour', '5', 'Baby Pink'),
  (25, 'HandlebarStemColour', '6', 'Tempest Blue'),
  (25, 'HandlebarStemColour', '8', 'Pall Mall White Gloss'),
  (25, 'HandlebarStemColour', '9', 'Blasted Titanium'),
  (25, 'HandlebarStemColour', 'A', 'Bumblebee Yellow'),
  (25, 'HandlebarStemColour', 'B', 'Black - Matt'),
  (25, 'HandlebarStemColour', 'D', 'Oxblood Red Gloss'),
  (25, 'HandlebarStemColour', 'E', 'Ocean Blue'),
  (25, 'HandlebarStemColour', 'F', 'Amethyst Lacquer'),
  (25, 'HandlebarStemColour', 'G', 'Racing Green - Matt'),
  (25, 'HandlebarStemColour', 'K', 'Black Lacquer - Gloss'),
  (25, 'HandlebarStemColour', 'M', 'Bronze Sky Metallic'),
  (25, 'HandlebarStemColour', 'N', 'Dune Sand'),
  (25, 'HandlebarStemColour', 'O', 'Bottle Green'),
  (25, 'HandlebarStemColour', 'R', 'Turkish Green - Matt'),
  (25, 'HandlebarStemColour', 'S', 'Papyrus White - Matt'),
  (25, 'HandlebarStemColour', 'T', 'Midnight Black Metallic'),
  (25, 'HandlebarStemColour', 'V', 'Bolt Blue Lacquer'),
  (25, 'HandlebarStemColour', 'W', 'Yuzu Lime'),
  (25, 'HandlebarStemColour', 'X', 'Special Colour X'),
  (25, 'HandlebarStemColour', 'Y', 'Special Colour Y'),
  (25, 'HandlebarStemColour', 'Z', 'Special Colour Z'),
  (25, 'HandlebarStemColour', 'J', 'Flamingo Pink'),
  (25, 'HandlebarStemColour', 'H', 'Lavender Matt'),
  (25, 'HandlebarStemColour', 'L', 'Metallic Blue Gloss'),
  (25, 'HandlebarStemColour', 'U', 'Palm Green'),
  (25, 'HandlebarStemColour', 'Q', 'Wine Red Matt'),
  (25, 'HandlebarStemColour', 'C', 'Veligo Blue'),
  (25, 'HandlebarStemColour', 'P', 'Pale Brown'),
  (25, 'HandlebarStemColour', '7', 'Azure Blue'),
  (26, 'HandlebarPinColour', '1', 'Lunar Ice'),
  (26, 'HandlebarPinColour', '2', 'Yellow Gloss'),
  (26, 'HandlebarPinColour', '3', 'Pure Orange Matt'),
  (26, 'HandlebarPinColour', '4', 'White - Gloss'),
  (26, 'HandlebarPinColour', '5', 'Baby Pink'),
  (26, 'HandlebarPinColour', '6', 'Tempest Blue'),
  (26, 'HandlebarPinColour', '7', 'Laurel Green Gloss'),
  (26, 'HandlebarPinColour', '9', 'Blasted Ti'),
  (26, 'HandlebarPinColour', 'A', 'Bumblebee Yellow'),
  (26, 'HandlebarPinColour', 'B', 'Black - Matt'),
  (26, 'HandlebarPinColour', 'D', 'Oxblood Red Gloss'),
  (26, 'HandlebarPinColour', 'E', 'Ocean Blue'),
  (26, 'HandlebarPinColour', 'F', 'Amethyst Lacquer'),
  (26, 'HandlebarPinColour', 'G', 'Racing Green - Matt'),
  (26, 'HandlebarPinColour', 'K', 'Black Lacquer - Gloss'),
  (26, 'HandlebarPinColour', 'M', 'Bronze Sky Metallic'),
  (26, 'HandlebarPinColour', 'N', 'Dune Sand'),
  (26, 'HandlebarPinColour', 'O', 'Bottle Green'),
  (26, 'HandlebarPinColour', 'R', 'Turkish Green - Matt'),
  (26, 'HandlebarPinColour', 'T', 'Midnight Black Metallic'),
  (26, 'HandlebarPinColour', 'V', 'Bolt Blue Lacquer'),
  (26, 'HandlebarPinColour', 'W', 'Sulphur Yellow'),
  (26, 'HandlebarPinColour', 'X', 'Special Colour X'),
  (26, 'HandlebarPinColour', 'Y', 'Special Colour Y'),
  (26, 'HandlebarPinColour', 'Z', 'Special Colour Z'),
  (26, 'HandlebarPinColour', 'J', 'Flamingo Pink'),
  (26, 'HandlebarPinColour', 'S', 'Gloss White'),
  (26, 'HandlebarPinColour', 'H', 'Lavender Matt'),
  (26, 'HandlebarPinColour', 'L', 'Metallic Blue Gloss'),
  (26, 'HandlebarPinColour', 'U', 'Palm Green'),
  (26, 'HandlebarPinColour', 'Q', 'Wine Red Matt'),
  (26, 'HandlebarPinColour', 'C', 'Veligo Blue'),
  (26, 'HandlebarPinColour', 'P', 'Pale Brown'),
  (26, 'HandlebarPinColour', '8', 'Purple Violet'),
  (27, 'FrontFrameColour', '1', 'Lunar Ice'),
  (27, 'FrontFrameColour', '4', 'Forest Green'),
  (27, 'FrontFrameColour', '5', 'Traildust White'),
  (27, 'FrontFrameColour', '6', 'Adventure Orange'),
  (27, 'FrontFrameColour', '7', 'Laurel Green Gloss'),
  (27, 'FrontFrameColour', '9', 'Blasted Ti'),
  (27, 'FrontFrameColour', 'B', 'Black - Matt'),
  (27, 'FrontFrameColour', 'C', 'Cerakote Ti Red'),
  (27, 'FrontFrameColour', 'F', 'Amethyst Lacquer'),
  (27, 'FrontFrameColour', 'G', 'Racing Green - Matt'),
  (27, 'FrontFrameColour', 'K', 'Black Lacquer - Gloss'),
  (27, 'FrontFrameColour', 'N', 'Dune Sand'),
  (27, 'FrontFrameColour', 'O', 'Bottle Green'),
  (27, 'FrontFrameColour', 'R', 'Turkish Green - Matt'),
  (27, 'FrontFrameColour', 'S', 'Papyrus White - Matt'),
  (27, 'FrontFrameColour', 'T', 'Midnight Black Metallic'),
  (27, 'FrontFrameColour', 'V', 'Bolt Blue Lacquer'),
  (27, 'FrontFrameColour', 'W', 'Sulphur Yellow'),
  (27, 'FrontFrameColour', 'X', 'Special Colour X'),
  (27, 'FrontFrameColour', 'Y', 'Special Colour Y'),
  (27, 'FrontFrameColour', 'Z', 'Special Colour Z'),
  (27, 'FrontFrameColour', '3', 'Space Black'),
  (27, 'FrontFrameColour', 'J', 'Flamingo Pink'),
  (27, 'FrontFrameColour', 'M', 'Metallic Green Gloss'),
  (27, 'FrontFrameColour', 'D', 'Cobalt Blue Lacquer'),
  (27, 'FrontFrameColour', 'H', 'Lavender Matt'),
  (27, 'FrontFrameColour', 'L', 'Metallic Blue Gloss'),
  (27, 'FrontFrameColour', 'U', 'Palm Green'),
  (27, 'FrontFrameColour', 'Q', 'Wine Red Matt'),
  (27, 'FrontFrameColour', '2', 'Beige Grey'),
  (27, 'FrontFrameColour', 'A', 'Pastel Violet'),
  (27, 'FrontFrameColour', 'P', 'Pale Brown'),
  (27, 'FrontFrameColour', '8', 'Purple Violet'),
  (27, 'FrontFrameColour', 'E', 'Vitality Pink'),
  (28, 'FrontForkColour', '1', 'Lunar Ice'),
  (28, 'FrontForkColour', '2', 'Yellow Gloss'),
  (28, 'FrontForkColour', '4', 'Forest Green'),
  (28, 'FrontForkColour', '5', 'Traildust White'),
  (28, 'FrontForkColour', '6', 'Adventure Orange'),
  (28, 'FrontForkColour', '7', 'Laurel Green Gloss'),
  (28, 'FrontForkColour', '9', 'Blasted Titanium'),
  (28, 'FrontForkColour', 'A', 'Bumblebee Yellow'),
  (28, 'FrontForkColour', 'B', 'Black - Matt'),
  (28, 'FrontForkColour', 'D', 'Oxblood Red Gloss'),
  (28, 'FrontForkColour', 'E', 'Ocean Blue'),
  (28, 'FrontForkColour', 'F', 'Amethyst Lacquer'),
  (28, 'FrontForkColour', 'G', 'Racing Green - Matt'),
  (28, 'FrontForkColour', 'K', 'Black Lacquer - Gloss'),
  (28, 'FrontForkColour', 'M', 'Bronze Sky Metallic'),
  (28, 'FrontForkColour', 'N', 'Dune Sand'),
  (28, 'FrontForkColour', 'O', 'Bottle Green'),
  (28, 'FrontForkColour', 'R', 'Turkish Green - Matt'),
  (28, 'FrontForkColour', 'S', 'Papyrus White - Matt'),
  (28, 'FrontForkColour', 'T', 'Midnight Black Metallic'),
  (28, 'FrontForkColour', 'V', 'Bolt Blue Lacquer'),
  (28, 'FrontForkColour', 'W', 'Sulphur Yellow'),
  (28, 'FrontForkColour', 'X', 'Special Colour X'),
  (28, 'FrontForkColour', 'Y', 'Special Colour Y'),
  (28, 'FrontForkColour', 'Z', 'Special Colour Z'),
  (28, 'FrontForkColour', '3', 'Space Black'),
  (28, 'FrontForkColour', 'J', 'Flamingo Pink'),
  (28, 'FrontForkColour', 'H', 'Lavender Matt'),
  (28, 'FrontForkColour', 'L', 'Piccadilly Blue'),
  (28, 'FrontForkColour', 'U', 'Palm Green'),
  (28, 'FrontForkColour', 'Q', 'Wine Red Matt'),
  (28, 'FrontForkColour', 'C', 'Veligo Blue'),
  (28, 'FrontForkColour', 'P', 'Pale Brown'),
  (28, 'FrontForkColour', '8', 'Purple Violet'),
  (29, 'Position29', '1', 'Code 1'),
  (30, 'Grade', '0', 'New'),
  (30, 'Grade', 'A', 'Grade A'),
  (30, 'Grade', 'B', 'Grade B'),
  (30, 'Grade', 'C', 'Grade C')
), seed as ( select digit_position, option_name, upper(code_value) as code_value, choice_value from seed_raw )
insert into cpq_import_rows (import_run_id, row_number, option_name, choice_value, digit_position, code_value, status, normalized_option_name, action_attempted)
select null, row_number() over(order by digit_position, option_name, code_value), option_name, choice_value, digit_position, code_value, 'imported', option_name, 'seed_delete111_xlsx' from seed
on conflict do nothing;
commit;
