-- Final cpq_products fallback cleanup wave: detach remaining cpq_products_flat compatibility fallback
-- from legacy cpq_products payload columns, then drop matched columns.
-- Evidence:
-- 1) runtime matrix reads consume cpq_products_flat projection columns, not raw cpq_products payload columns,
-- 2) push/import persists these attributes via cpq_product_attributes + cpq_import_rows,
-- 3) cpq_products_flat fallback can safely resolve from normalized attributes for this legacy subset.

create or replace view cpq_products_flat as
select
  p.id,
  p.sku_code,
  p.cpq_ruleset,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('ProductAssist')) as product_assist,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('ProductFamily')) as product_family,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('ProductLine')) as product_line,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('ProductModel')) as product_model,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('ProductType')) as product_type,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('HandlebarType')) as handlebar_type,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('Speeds')) as speeds,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('MudguardsAndRack')) as mudguards_and_rack,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('Territory')) as territory,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('MainFrameColour')) as main_frame_colour,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('RearFrameColour')) as rear_frame_colour,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('FrontCarrierBlock')) as front_carrier_block,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('Lighting')) as lighting,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('SaddleHeight')) as saddle_height,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('GearRatio')) as gear_ratio,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('Saddle')) as saddle,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('Tyre')) as tyre,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('Brakes')) as brakes,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('Pedals')) as pedals,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('Saddlebag')) as saddlebag,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('Suspension')) as suspension,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('BikeType')) as bike_type,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('Toolkit')) as toolkit,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('SaddleLight')) as saddle_light,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('ConfigCode')) as config_code,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('OptionBox')) as option_box,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('FrameMaterial')) as frame_material,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('FrameSet')) as frame_set,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('ComponentColour')) as component_colour,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('OnBikeAccessories')) as on_bike_accessories,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('HandlebarStemColour')) as handlebar_stem_colour,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('HandlebarPinColour')) as handlebar_pin_colour,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('FrontFrameColour')) as front_frame_colour,
  max(ir.choice_value) filter (where lower(pa.option_name) = lower('FrontForkColour')) as front_fork_colour
from cpq_products p
left join cpq_product_attributes pa on pa.cpq_product_id = p.id
left join cpq_import_rows ir on ir.id = pa.cpq_import_row_id
group by p.id;

alter table if exists cpq_products
  drop column if exists handlebar_type,
  drop column if exists speeds,
  drop column if exists mudguardsandrack,
  drop column if exists territory,
  drop column if exists mainframecolour,
  drop column if exists rearframecolour,
  drop column if exists frontcarrierblock,
  drop column if exists lighting,
  drop column if exists saddleheight,
  drop column if exists gearratio,
  drop column if exists saddle,
  drop column if exists tyre,
  drop column if exists brakes,
  drop column if exists pedals,
  drop column if exists saddlebag,
  drop column if exists suspension,
  drop column if exists biketype,
  drop column if exists toolkit,
  drop column if exists saddlelight,
  drop column if exists configcode,
  drop column if exists optionbox,
  drop column if exists framematerial,
  drop column if exists frameset,
  drop column if exists componentcolour,
  drop column if exists onbikeaccessories,
  drop column if exists handlebarstemcolour,
  drop column if exists handlebarpincolour,
  drop column if exists frontframecolour,
  drop column if exists frontforkcolour;

-- Rollback (additive, reversible):
-- alter table if exists cpq_products
--   add column if not exists handlebar_type text,
--   add column if not exists speeds text,
--   add column if not exists mudguardsandrack text,
--   add column if not exists territory text,
--   add column if not exists mainframecolour text,
--   add column if not exists rearframecolour text,
--   add column if not exists frontcarrierblock text,
--   add column if not exists lighting text,
--   add column if not exists saddleheight text,
--   add column if not exists gearratio text,
--   add column if not exists saddle text,
--   add column if not exists tyre text,
--   add column if not exists brakes text,
--   add column if not exists pedals text,
--   add column if not exists saddlebag text,
--   add column if not exists suspension text,
--   add column if not exists biketype text,
--   add column if not exists toolkit text,
--   add column if not exists saddlelight text,
--   add column if not exists configcode text,
--   add column if not exists optionbox text,
--   add column if not exists framematerial text,
--   add column if not exists frameset text,
--   add column if not exists componentcolour text,
--   add column if not exists onbikeaccessories text,
--   add column if not exists handlebarstemcolour text,
--   add column if not exists handlebarpincolour text,
--   add column if not exists frontframecolour text,
--   add column if not exists frontforkcolour text;
--
-- create or replace view cpq_products_flat as
-- select
--   p.id,
--   p.sku_code,
--   p.cpq_ruleset,
--   max(ir.choice_value) filter (where lower(pa.option_name) = lower('ProductAssist')) as product_assist,
--   max(ir.choice_value) filter (where lower(pa.option_name) = lower('ProductFamily')) as product_family,
--   max(ir.choice_value) filter (where lower(pa.option_name) = lower('ProductLine')) as product_line,
--   max(ir.choice_value) filter (where lower(pa.option_name) = lower('ProductModel')) as product_model,
--   max(ir.choice_value) filter (where lower(pa.option_name) = lower('ProductType')) as product_type,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('HandlebarType')), p.handlebar_type) as handlebar_type,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('Speeds')), p.speeds) as speeds,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('MudguardsAndRack')), p.mudguardsandrack) as mudguards_and_rack,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('Territory')), p.territory) as territory,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('MainFrameColour')), p.mainframecolour) as main_frame_colour,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('RearFrameColour')), p.rearframecolour) as rear_frame_colour,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('FrontCarrierBlock')), p.frontcarrierblock) as front_carrier_block,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('Lighting')), p.lighting) as lighting,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('SaddleHeight')), p.saddleheight) as saddle_height,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('GearRatio')), p.gearratio) as gear_ratio,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('Saddle')), p.saddle) as saddle,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('Tyre')), p.tyre) as tyre,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('Brakes')), p.brakes) as brakes,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('Pedals')), p.pedals) as pedals,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('Saddlebag')), p.saddlebag) as saddlebag,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('Suspension')), p.suspension) as suspension,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('BikeType')), p.biketype) as bike_type,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('Toolkit')), p.toolkit) as toolkit,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('SaddleLight')), p.saddlelight) as saddle_light,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('ConfigCode')), p.configcode) as config_code,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('OptionBox')), p.optionbox) as option_box,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('FrameMaterial')), p.framematerial) as frame_material,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('FrameSet')), p.frameset) as frame_set,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('ComponentColour')), p.componentcolour) as component_colour,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('OnBikeAccessories')), p.onbikeaccessories) as on_bike_accessories,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('HandlebarStemColour')), p.handlebarstemcolour) as handlebar_stem_colour,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('HandlebarPinColour')), p.handlebarpincolour) as handlebar_pin_colour,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('FrontFrameColour')), p.frontframecolour) as front_frame_colour,
--   coalesce(max(ir.choice_value) filter (where lower(pa.option_name) = lower('FrontForkColour')), p.frontforkcolour) as front_fork_colour
-- from cpq_products p
-- left join cpq_product_attributes pa on pa.cpq_product_id = p.id
-- left join cpq_import_rows ir on ir.id = pa.cpq_import_row_id
-- group by p.id;
